### ISSUE TITLE
Unable to compile on FreeBSD 13.3

### ISSUE THREAD

**Issue by 35gh** [airdcpp-web/airdcpp-webclient#504]
### Current UI and client versions:

Web Client 2.13.3 / Web UI 2.13.1
cmake version 3.31.6
websocketpp: 0.8.2

### Operating system:

FreeBSD airdcpp 13.3-RELEASE-p4 FreeBSD 13.3-RELEASE-p4 n257491-41f6a830f8e TRUENAS amd64

### Steps to reproduce the issue:

I get the following errors during compilation:

{code}

[ 63%] Building C object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/microtar/microtar.c.o
In file included from <built-in>:1:
In file included from /root/airdcpp-webclient/airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/cmake_pch.hxx:5:
In file included from /root/airdcpp-webclient/airdcpp-webapi/stdinc.h:29:
In file included from /usr/local/include/websocketpp/config/asio.hpp:32:
In file included from /usr/local/include/websocketpp/transport/asio/endpoint.hpp:32:
/usr/local/include/websocketpp/transport/asio/connection.hpp:89:24: error: no type named 'io_service' in namespace 'websocketpp::lib::asio'
   89 |     typedef lib::asio::io_service * io_service_ptr;
      |             ~~~~~~~~~~~^
/usr/local/include/websocketpp/transport/asio/connection.hpp:91:40: error: no member named 'io_service' in namespace 'websocketpp::lib::asio'
   91 |     typedef lib::shared_ptr<lib::asio::io_service::strand> strand_ptr;
      |                             ~~~~~~~~~~~^
/usr/local/include/websocketpp/transport/asio/connection.hpp:315:17: error: no matching constructor for initialization of 'lib::asio::steady_timer' (aka 'basic_waitable_timer<chrono::steady_clock>')
  315 |             new lib::asio::steady_timer(
      |                 ^
  316 |                 *m_io_service,
      |                 ~~~~~~~~~~~~~~
  317 |                 lib::asio::milliseconds(duration))
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_waitable_timer.hpp:232:12: note: candidate constructor template not viable: no known conversion from 'std::chrono::milliseconds' (aka 'duration<long long, ratio<1LL, 1000LL>>') to 'const time_point' (aka 'const time_point<std::chrono::steady_clock, duration<long long, ratio<1LL, 1000000000LL>>>') for 2nd argument
  232 |   explicit basic_waitable_timer(ExecutionContext& context,
      |            ^
  233 |       const time_point& expiry_time,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_waitable_timer.hpp:254:3: note: candidate constructor not viable: no known conversion from 'int' to 'const executor_type' (aka 'const boost::asio::any_io_executor') for 1st argument
  254 |   basic_waitable_timer(const executor_type& ex, const duration& expiry_time)
      |   ^                    ~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_waitable_timer.hpp:212:3: note: candidate constructor not viable: no known conversion from 'int' to 'const executor_type' (aka 'const boost::asio::any_io_executor') for 1st argument
  212 |   basic_waitable_timer(const executor_type& ex, const time_point& expiry_time)
      |   ^                    ~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_waitable_timer.hpp:194:12: note: candidate template ignored: substitution failure [with ExecutionContext = int]: no type named 'type' in 'boost::asio::constraint<false>'
  194 |   explicit basic_waitable_timer(ExecutionContext& context,
      |            ^
/usr/local/include/boost/asio/basic_waitable_timer.hpp:275:12: note: candidate template ignored: substitution failure [with ExecutionContext = int]: no type named 'type' in 'boost::asio::constraint<false>'
  275 |   explicit basic_waitable_timer(ExecutionContext& context,
      |            ^
/usr/local/include/boost/asio/basic_waitable_timer.hpp:338:3: note: candidate template ignored: could not match 'basic_waitable_timer<steady_clock, wait_traits<steady_clock>, Executor1>' against 'int'
  338 |   basic_waitable_timer(
      |   ^
/usr/local/include/boost/asio/basic_waitable_timer.hpp:178:12: note: candidate constructor not viable: requires single argument 'ex', but 2 arguments were provided
  178 |   explicit basic_waitable_timer(const executor_type& ex)
      |            ^                    ~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_waitable_timer.hpp:299:3: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
  299 |   basic_waitable_timer(basic_waitable_timer&& other)
      |   ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_waitable_timer.hpp:601:3: note: candidate constructor not viable: requires 1 argument, but 2 were provided
  601 |   basic_waitable_timer(const basic_waitable_timer&) = delete;
      |   ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from <built-in>:1:
In file included from /root/airdcpp-webclient/airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/cmake_pch.hxx:5:
In file included from /root/airdcpp-webclient/airdcpp-webapi/stdinc.h:29:
In file included from /usr/local/include/websocketpp/config/asio.hpp:32:
In file included from /usr/local/include/websocketpp/transport/asio/endpoint.hpp:32:
/usr/local/include/websocketpp/transport/asio/connection.hpp:321:45: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
  321 |             new_timer->async_wait(m_strand->wrap(lib::bind(
      |                                   ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:465:21: error: member reference base type 'strand_ptr' (aka 'int') is not a structure or union
  465 |             m_strand.reset(new lib::asio::io_service::strand(*io_service));
      |             ~~~~~~~~^~~~~~
/usr/local/include/websocketpp/transport/asio/connection.hpp:465:43: error: 'io_service' is not a class, namespace, or enumeration
  465 |             m_strand.reset(new lib::asio::io_service::strand(*io_service));
      |                                           ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:461:47: note: 'io_service' declared here
  461 |     lib::error_code init_asio (io_service_ptr io_service) {
      |                                               ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:576:58: error: no member named 'expires_from_now' in 'boost::asio::basic_waitable_timer<std::chrono::steady_clock>'
  576 |             (post_timer && lib::asio::is_neg(post_timer->expires_from_now())))
      |                                              ~~~~~~~~~~~~^
/usr/local/include/websocketpp/transport/asio/connection.hpp:632:27: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
  632 |                 m_strand->wrap(lib::bind(
      |                 ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:716:27: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
  716 |                 m_strand->wrap(lib::bind(
      |                 ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:844:27: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
  844 |                 m_strand->wrap(make_custom_alloc_handler(
      |                 ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:913:27: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
  913 |                 m_strand->wrap(make_custom_alloc_handler(
      |                 ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:950:27: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
  950 |                 m_strand->wrap(make_custom_alloc_handler(
      |                 ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:1015:25: error: member reference base type 'int' is not a structure or union
 1015 |             m_io_service->post(m_strand->wrap(handler));
      |             ~~~~~~~~~~~~^ ~~~~
/usr/local/include/websocketpp/transport/asio/connection.hpp:1015:42: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
 1015 |             m_io_service->post(m_strand->wrap(handler));
      |                                ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:1017:25: error: member reference base type 'int' is not a structure or union
 1017 |             m_io_service->post(handler);
      |             ~~~~~~~~~~~~^ ~~~~
/usr/local/include/websocketpp/transport/asio/connection.hpp:1024:25: error: member reference base type 'int' is not a structure or union
 1024 |             m_io_service->post(m_strand->wrap(handler));
      |             ~~~~~~~~~~~~^ ~~~~
/usr/local/include/websocketpp/transport/asio/connection.hpp:1024:42: error: member reference type 'strand_ptr' (aka 'int') is not a pointer
 1024 |             m_io_service->post(m_strand->wrap(handler));
      |                                ~~~~~~~~  ^
/usr/local/include/websocketpp/transport/asio/connection.hpp:1026:25: error: member reference base type 'int' is not a structure or union
 1026 |             m_io_service->post(handler);
      |             ~~~~~~~~~~~~^ ~~~~
/usr/local/include/websocketpp/transport/asio/connection.hpp:1098:47: error: no member named 'expires_from_now' in 'boost::asio::basic_waitable_timer<std::chrono::steady_clock>'
 1098 |             lib::asio::is_neg(shutdown_timer->expires_from_now()))
      |                               ~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
--- airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/cmake_pch.hxx.pch ---
*** [airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/cmake_pch.hxx.pch] Error code 1

make[2]: stopped in /root/airdcpp-webclient
1 error

make[2]: stopped in /root/airdcpp-webclient
--- airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/all ---
*** [airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/all] Error code 2

make[1]: stopped in /root/airdcpp-webclient
1 error

make[1]: stopped in /root/airdcpp-webclient
*** [all] Error code 2

make: stopped in /root/airdcpp-webclient
1 error

make: stopped in /root/airdcpp-webclient

{code}

**Comment by maksis** [comment]
See https://github.com/zaphoyd/websocketpp/issues/1157

You can make it compile by cloning a custom websocketpp repository containing the fix:

`git clone -b develop https://github.com/amini-allight/websocketpp.git`
